const express = require("express")
const API = require("../controller/controller")
const { requireCookie, checkUser } = require("../isAuth/auth")

const router = express.Router();

router.get("/", API.getAdminLogin)
router.post("/login", requireCookie, API.loginAdmin)
router.get("/register", API.getAdminRegister)
router.post("/register", API.registerAdmin)
router.get("/dashboard", checkUser, API.getAdminDashboard)
router.post("/wallet", checkUser, API.createWalletAddress)
router.put("/wallet", checkUser, API.changeWalletAddress)
router.get("/traders", checkUser, API.getTopTraders)
router.post("/traders", checkUser, API.createTopTrader)
router.get("/createtrader", checkUser, API.getTraderForm)
router.get("/updatetrader/:id", checkUser, API.getupdateTrader)
router.post("/updatetrader/:id", checkUser, API.updateTrader)
router.get("/user", checkUser, API.getUsers)
router.get("/manage/block/:id", checkUser, API.blockUser)
router.get("/manage/unblock/:id", checkUser, API.unblockUser)
router.get("/manage/delete/:id", checkUser, API.deleteUser)
router.get("/manage/:id", checkUser, API.manageUser)
router.put("/manage/signal/:id", checkUser, API.manageSignal)
router.get("/manage/edit/:id", checkUser, API.editUser)
router.post("/manage/edit/:id", checkUser, API.updateUser)
router.get("/manage/finance/:id", checkUser, API.getUserFinance)
router.get("/manage/finance/credit/:id", checkUser, API.creditUserForm)
router.post("/manage/finance/credit/:id", checkUser, API.credit)
router.post("/manage/finance/debit/:id", checkUser, API.debit)
router.get("/manage/finance/credit/:id/:paymentid", checkUser, API.getUserCreditForm)
router.post("/manage/finance/credit/:id/:paymentid", checkUser, API.creditUser)
router.post("/manage/finance/debit/:id/:paymentid", checkUser, API.debitUser)
router.post("/manage/pay/:id", checkUser, API.userPaid)
router.get("/manage/notification/:id", checkUser, API.getNotification)
router.post("/approve/:id", checkUser, API.approvePayment)
router.post("/decline/:id", checkUser, API.declinePayment)

module.exports = router;